# Generated by Django 2.1.7 on 2019-03-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('tweet_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Tweet Id')),
                ('tweet_date', models.DateTimeField()),
                ('user_id', models.CharField(max_length=25, verbose_name='User Id')),
                ('user_name', models.CharField(max_length=50, verbose_name='User Name')),
                ('content', models.TextField()),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('accuracy', models.IntegerField(default=0)),
                ('in_accuracy_category', models.CharField(blank=True, max_length=50)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
    ]
