# Generated by Django 2.1.7 on 2019-03-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='tweet_date',
            field=models.DateTimeField(default=''),
        ),
    ]
