# Generated by Django 2.1.7 on 2019-03-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0002_auto_20190314_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='tweet_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
