# Generated by Django 2.1.7 on 2019-03-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0003_auto_20190314_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='tweet_date',
            field=models.DateTimeField(),
        ),
    ]
