# Generated by Django 2.1.7 on 2019-03-14 16:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InAccuracyCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tweet_id', models.CharField(max_length=20, verbose_name='Tweet Id')),
                ('student_id', models.IntegerField(blank=True)),
                ('student_handle', models.CharField(max_length=50, verbose_name='User Name')),
                ('description', models.TextField(blank=True)),
                ('tweet_date', models.DateTimeField(verbose_name='Tweet Date')),
                ('accuracy', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('comments', models.TextField(blank=True, null=True)),
                ('is_pending', models.BooleanField(default=True)),
                ('inaccuracy_category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reflections.InAccuracyCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('subject_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reflections.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='reflection',
            name='subject',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='reflections.Subject'),
        ),
        migrations.AddField(
            model_name='reflection',
            name='topic',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reflections.Topic'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('id', 'subject_id')},
        ),
        migrations.AlterUniqueTogether(
            name='reflection',
            unique_together={('id', 'student_id')},
        ),
    ]
