# Generated by Django 2.1.7 on 2019-02-27 03:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflection',
            name='accuracy',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='inaccuracy_category',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='reflections.InAccuracyCategory'),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='topic',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='reflections.Topic'),
        ),
    ]
