# Generated by Django 2.1.7 on 2019-03-14 21:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reflection',
            name='tweet_date',
        ),
        migrations.RemoveField(
            model_name='reflection',
            name='tweet_id',
        ),
        migrations.AddField(
            model_name='reflection',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reflection',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='student_handle',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='student_id',
            field=models.CharField(max_length=50),
        ),
    ]
