# Generated by Django 2.1.7 on 2019-03-17 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0002_auto_20190314_2154'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reflection',
            unique_together={('id', 'student_id', 'subject')},
        ),
    ]
