# Generated by Django 2.1.7 on 2019-03-17 01:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0003_auto_20190317_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflection',
            name='tweet_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reflection',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='reflection',
            unique_together={('tweet_id', 'student_id', 'subject')},
        ),
    ]
