# Generated by Django 2.1.7 on 2019-03-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0004_auto_20190317_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflection',
            name='tweet_id',
            field=models.CharField(max_length=50),
        ),
    ]
