# Generated by Django 2.1.7 on 2019-02-27 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InAccuracyCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('description', models.TextField()),
                ('accuracy', models.IntegerField()),
                ('inaccuracy_category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='reflections.InAccuracyCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('subject_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reflections.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='reflection',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reflections.Subject'),
        ),
        migrations.AddField(
            model_name='reflection',
            name='topic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reflections.Topic'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('id', 'subject_id')},
        ),
        migrations.AlterUniqueTogether(
            name='reflection',
            unique_together={('id', 'student_id')},
        ),
    ]
