# Generated by Django 2.1.7 on 2019-03-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0004_auto_20190227_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflection',
            name='comments',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reflection',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
